version: '3.8'

services:
  jesus-arias:
    build: ./jesus-arias
    container_name: contenedor-jesus

  Ángel:
    build:
      context: ./Equipo/Ángel
    container_name: Ángel_container
santiago_cuevas:
    build:
      context: .
      dockerfile: Equipo/Santiago_Cuevas/Dockerfile
    container_name: santiago_cuevas_container

  Antonio:
    build:
      context: ./Equipo/Antonio
      container_name: Antonio_container


  Steve:
    build:
      context: ./Steve
      dockerfile: Dockerfile
    container_name: mi-imagen-steve
   
 networks:
      - default
