services:

 # Alejandro-Villodres:
   # image: mi-app-python

  sotos:
    build: ./Sotos
    container_name: Sotos

  salva-lopez:
    build: ./Salva-Lopez
    container_name: Salva-Lopez

  cristobal:
    build: ./cristobal
    container_name: cristobal

  jesus:
    build: ./jesus_ojeda
    container_name: jesus_ojeda

  javier:
    build: ./Javier
    container_name: Javier

  paula:
    build: ./paula_barranco
    container_name: paula

  mario:
    build: ./Mario
    container_name: Mario
    
  salvador_malia:
    build: ./Salvador_Malia
    container_name: Salvador_Malia 

  david_raez:
    build: ./david_raez
    container_name: David_Raez 


  contenedor-damian:
    build: ./Damian
    container_name: contenedor-damian

